dotnet nuget delete YJC.Toolkit.Core 5.5.0 -k oy2egvmi54reilm5xs7agstzrbccucyuvggujnjofausbi -s https://api.nuget.org/v3/index.json --non-interactive
dotnet nuget delete YJC.Toolkit.MetaData 5.5.0 -k oy2egvmi54reilm5xs7agstzrbccucyuvggujnjofausbi -s https://api.nuget.org/v3/index.json --non-interactive
dotnet nuget delete YJC.Toolkit.Data 5.5.0 -k oy2egvmi54reilm5xs7agstzrbccucyuvggujnjofausbi -s https://api.nuget.org/v3/index.json --non-interactive 
dotnet nuget delete YJC.Toolkit.AdoData 5.5.0 -k oy2egvmi54reilm5xs7agstzrbccucyuvggujnjofausbi -s https://api.nuget.org/v3/index.json --non-interactive
dotnet nuget delete YJC.Toolkit.Cache 5.5.0 -k oy2egvmi54reilm5xs7agstzrbccucyuvggujnjofausbi -s https://api.nuget.org/v3/index.json --non-interactive
dotnet nuget delete YJC.Toolkit.RedisCache 5.5.0 -k oy2egvmi54reilm5xs7agstzrbccucyuvggujnjofausbi -s https://api.nuget.org/v3/index.json --non-interactive
dotnet nuget delete YJC.Toolkit.MsSqlClient 5.5.0 -k oy2egvmi54reilm5xs7agstzrbccucyuvggujnjofausbi -s https://api.nuget.org/v3/index.json --non-interactive
dotnet nuget delete YJC.Toolkit.MySql 5.5.0 -k oy2egvmi54reilm5xs7agstzrbccucyuvggujnjofausbi -s https://api.nuget.org/v3/index.json --non-interactive
dotnet nuget delete YJC.Toolkit.SqlClient 5.5.0 -k oy2egvmi54reilm5xs7agstzrbccucyuvggujnjofausbi -s https://api.nuget.org/v3/index.json --non-interactive
dotnet nuget delete YJC.Toolkit.Evaluator 5.5.0 -k oy2egvmi54reilm5xs7agstzrbccucyuvggujnjofausbi -s https://api.nuget.org/v3/index.json --non-interactive
dotnet nuget delete YJC.Toolkit.Web.Common 5.5.0 -k oy2egvmi54reilm5xs7agstzrbccucyuvggujnjofausbi -s https://api.nuget.org/v3/index.json --non-interactive
dotnet nuget delete YJC.Toolkit.WebApp 5.5.0 -k oy2egvmi54reilm5xs7agstzrbccucyuvggujnjofausbi -s https://api.nuget.org/v3/index.json --non-interactive
dotnet nuget delete YJC.Toolkit.Razor 5.5.0 -k oy2egvmi54reilm5xs7agstzrbccucyuvggujnjofausbi -s https://api.nuget.org/v3/index.json --non-interactive
dotnet nuget delete YJC.Toolkit.Razor.Web.Common 5.5.0 -k oy2egvmi54reilm5xs7agstzrbccucyuvggujnjofausbi -s https://api.nuget.org/v3/index.json --non-interactive
dotnet nuget delete YJC.Toolkit.Razor.Web 5.5.0 -k oy2egvmi54reilm5xs7agstzrbccucyuvggujnjofausbi -s https://api.nuget.org/v3/index.json --non-interactive
dotnet nuget delete YJC.Toolkit.Excel 5.5.0 -k oy2egvmi54reilm5xs7agstzrbccucyuvggujnjofausbi -s https://api.nuget.org/v3/index.json --non-interactive
dotnet nuget delete YJC.Toolkit.Excel.Web 5.5.0 -k oy2egvmi54reilm5xs7agstzrbccucyuvggujnjofausbi -s https://api.nuget.org/v3/index.json --non-interactive
dotnet nuget delete YJC.Toolkit.JWTLib 5.5.0 -k oy2egvmi54reilm5xs7agstzrbccucyuvggujnjofausbi -s https://api.nuget.org/v3/index.json --non-interactive
dotnet nuget delete YJC.Toolkit.JWT 5.5.0 -k oy2egvmi54reilm5xs7agstzrbccucyuvggujnjofausbi -s https://api.nuget.org/v3/index.json --non-interactive