dotnet pack Core\YJC.Toolkit.Core\YJC.Toolkit.Core.21.csproj -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg --include-source
dotnet pack Core\YJC.Toolkit.MetaData\YJC.Toolkit.MetaData.21.csproj -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg --include-source
dotnet pack Data\YJC.Toolkit.Data\YJC.Toolkit.Data.21.csproj -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg --include-source
dotnet pack Data\YJC.Toolkit.AdoData\YJC.Toolkit.AdoData.21.csproj -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg --include-source
dotnet pack Core\YJC.Toolkit.Cache\YJC.Toolkit.Cache.21.csproj -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg --include-source
dotnet pack Core\YJC.Toolkit.RedisCache\YJC.Toolkit.RedisCache.21.csproj -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg --include-source
dotnet pack Data\YJC.Toolkit.MsSqlClient\YJC.Toolkit.MsSqlClient.21.csproj -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg --include-source
dotnet pack Data\YJC.Toolkit.MySql\YJC.Toolkit.MySql.21.csproj -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg --include-source
dotnet pack Data\YJC.Toolkit.SqlClient\YJC.Toolkit.SqlClient.21.csproj -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg --include-source
dotnet pack CoreData\YJC.Toolkit.Evaluator\YJC.Toolkit.Evaluator.31.csproj -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg --include-source
dotnet pack Data\YJC.Toolkit.Web.Common\YJC.Toolkit.Web.Common.21.csproj -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg --include-source
dotnet pack CoreWeb\YJC.Toolkit.WebApp\YJC.Toolkit.WebApp.31.csproj -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg --include-source
dotnet pack Data\YJC.Toolkit.Razor\YJC.Toolkit.Razor.21.csproj -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg --include-source
dotnet pack Data\YJC.Toolkit.Razor.Web.Common\YJC.Toolkit.Razor.Web.Common.21.csproj -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg --include-source
dotnet pack CoreWeb\YJC.Toolkit.Razor.Web\YJC.Toolkit.Razor.Web.31.csproj -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg --include-source
dotnet pack Data\YJC.Toolkit.Excel\YJC.Toolkit.Excel.21.csproj -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg --include-source
dotnet pack CoreWeb\YJC.Toolkit.Excel.Web\YJC.Toolkit.Excel.Web.31.csproj -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg --include-source
dotnet pack Data\JoseJWT\YJC.Toolkit.JWTLib.21.csproj -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg --include-source
dotnet pack Data\YJC.Toolkit.JWT\YJC.Toolkit.JWT.21.csproj -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg --include-source
dotnet pack CoreApp\YJC.Toolkit.Core.ToolApp\YJC.Toolkit.Core.ToolApp.31.csproj -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg --include-source
dotnet pack CoreApp\YJC.Toolkit.Core.ConsoleApp\YJC.Toolkit.Core.ConsoleApp.31.csproj -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg --include-source
dotnet pack CoreApp\YJC.Toolkit.Core.TestApp\YJC.Toolkit.Core.TestApp.21.csproj -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg --include-source

dotnet pack Workflow\YJC.Toolkit.UserIntf\YJC.Toolkit.UserIntf.21.csproj -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg --include-source
dotnet pack Workflow\YJC.Toolkit.SimpleWorkflow\YJC.Toolkit.SimpleWorkflow.21.csproj -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg --include-source
dotnet pack Workflow\YJC.Toolkit.SimpleWorkflow.Web\YJC.Toolkit.SimpleWorkflow.Web.31.csproj -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg --include-source
dotnet pack Data\YJC.Toolkit.HtmlExtension\YJC.Toolkit.HtmlExtension.21.csproj -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg --include-source
dotnet pack Data\YJC.Toolkit.Tenant\YJC.Toolkit.Tenant.21.csproj -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg --include-source
dotnet pack CoreData\YJC.Toolkit.AliyunOSS\YJC.Toolkit.AliyunOSS.31.csproj -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg --include-source

dotnet pack IM\YJC.Toolkit.IM\YJC.Toolkit.IM.31.csproj -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg --include-source
dotnet pack IM\YJC.Toolkit.DingTalk\YJC.Toolkit.DingTalk.31.csproj -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg --include-source
dotnet pack IM\YJC.Toolkit.Weixin2.Common\YJC.Toolkit.Weixin2.Common.31.csproj -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg --include-source
dotnet pack IM\YJC.Toolkit.Weixin2.WeChat\YJC.Toolkit.Weixin2.WeChat.31.csproj -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg --include-source
dotnet pack IM\YJC.Toolkit.Weixin2.WeChat.Data\YJC.Toolkit.Weixin2.WeChat.Data.31.csproj -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg --include-source
dotnet pack IM\YJC.Toolkit.Weixin2.WeChat.Web\YJC.Toolkit.Weixin2.WeChat.Web.31.csproj -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg --include-source
dotnet pack IM\YJC.Toolkit.Weixin2.WeCorp\YJC.Toolkit.Weixin2.WeCorp.31.csproj -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg --include-source