dotnet pack Core\YJC.Toolkit.Core\YJC.Toolkit.Core.csproj -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg --include-source
dotnet pack Core\YJC.Toolkit.MetaData\YJC.Toolkit.MetaData.csproj -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg --include-source
dotnet pack Data\YJC.Toolkit.Data\YJC.Toolkit.Data.csproj -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg --include-source
dotnet pack Data\YJC.Toolkit.AdoData\YJC.Toolkit.AdoData.csproj -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg --include-source
dotnet pack Core\YJC.Toolkit.Cache\YJC.Toolkit.Cache.csproj -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg --include-source
dotnet pack Core\YJC.Toolkit.RedisCache\YJC.Toolkit.RedisCache.csproj -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg --include-source
dotnet pack Data\YJC.Toolkit.MsSqlClient\YJC.Toolkit.MsSqlClient.csproj -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg --include-source
dotnet pack Data\YJC.Toolkit.MySql\YJC.Toolkit.MySql.csproj -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg --include-source
dotnet pack Data\YJC.Toolkit.SqlClient\YJC.Toolkit.SqlClient.csproj -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg --include-source
dotnet pack CoreData\YJC.Toolkit.Evaluator\YJC.Toolkit.Evaluator.csproj -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg --include-source
dotnet pack Data\YJC.Toolkit.Web.Common\YJC.Toolkit.Web.Common.csproj -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg --include-source
dotnet pack CoreWeb\YJC.Toolkit.WebApp\YJC.Toolkit.WebApp.csproj -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg --include-source
dotnet pack Data\YJC.Toolkit.Razor\YJC.Toolkit.Razor.csproj -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg --include-source
dotnet pack Data\YJC.Toolkit.Razor.Web.Common\YJC.Toolkit.Razor.Web.Common.csproj -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg --include-source
dotnet pack CoreWeb\YJC.Toolkit.Razor.Web\YJC.Toolkit.Razor.Web.csproj -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg --include-source
dotnet pack Data\YJC.Toolkit.Excel\YJC.Toolkit.Excel.csproj -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg --include-source
dotnet pack CoreWeb\YJC.Toolkit.Excel.Web\YJC.Toolkit.Excel.Web.csproj -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg --include-source
dotnet pack Data\JoseJWT\YJC.Toolkit.JWTLib.csproj -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg --include-source
dotnet pack Data\YJC.Toolkit.JWT\YJC.Toolkit.JWT.csproj -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg --include-source
dotnet pack CoreApp\YJC.Toolkit.Core.ToolApp\YJC.Toolkit.Core.ToolApp.csproj -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg --include-source
dotnet pack CoreApp\YJC.Toolkit.Core.ConsoleApp\YJC.Toolkit.Core.ConsoleApp.csproj -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg --include-source
dotnet pack CoreApp\YJC.Toolkit.Core.TestApp\YJC.Toolkit.Core.TestApp.csproj -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg --include-source

dotnet pack Workflow\YJC.Toolkit.UserIntf\YJC.Toolkit.UserIntf.csproj -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg --include-source
dotnet pack Workflow\YJC.Toolkit.SimpleWorkflow\YJC.Toolkit.SimpleWorkflow.csproj -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg --include-source
dotnet pack Workflow\YJC.Toolkit.SimpleWorkflow.Web\YJC.Toolkit.SimpleWorkflow.Web.csproj -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg --include-source
dotnet pack Data\YJC.Toolkit.HtmlExtension\YJC.Toolkit.HtmlExtension.csproj -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg --include-source
dotnet pack Data\YJC.Toolkit.Tenant\YJC.Toolkit.Tenant.csproj -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg --include-source
dotnet pack CoreData\YJC.Toolkit.AliyunOSS\YJC.Toolkit.AliyunOSS.csproj -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg --include-source

dotnet pack IM\YJC.Toolkit.IM\YJC.Toolkit.IM.csproj -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg --include-source
dotnet pack IM\YJC.Toolkit.DingTalk\YJC.Toolkit.DingTalk.csproj -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg --include-source
dotnet pack IM\YJC.Toolkit.Weixin2.Common\YJC.Toolkit.Weixin2.Common.csproj -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg --include-source
dotnet pack IM\YJC.Toolkit.Weixin2.WeChat\YJC.Toolkit.Weixin2.WeChat.csproj -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg --include-source
dotnet pack IM\YJC.Toolkit.Weixin2.WeChat.Data\YJC.Toolkit.Weixin2.WeChat.Data.csproj -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg --include-source
dotnet pack IM\YJC.Toolkit.Weixin2.WeChat.Web\YJC.Toolkit.Weixin2.WeChat.Web.csproj -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg --include-source
dotnet pack IM\YJC.Toolkit.Weixin2.WeCorp\YJC.Toolkit.Weixin2.WeCorp.csproj -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg --include-source