//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YJC.Toolkit {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class XmlSegment {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal XmlSegment() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YJC.Toolkit.XmlSegment", typeof(XmlSegment).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;tk:Table ListStyle=&quot;Table&quot; Action=&quot;List&quot; xmlns:tk=&quot;http://www.qdocuments.net&quot;&gt;
        ///  &lt;tk:SingleXmlMetaData DataXml=&quot;Workflow/ApproveHistory.xml&quot;/&gt;
        ///&lt;/tk:Table&gt; 的本地化字符串。
        /// </summary>
        internal static string ApproveContentXml {
            get {
                return ResourceManager.GetString("ApproveContentXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;tk:Table ListStyle=&quot;Normal&quot; Action=&quot;Update&quot; Status=&quot;Update&quot; xmlns:tk=&quot;http://www.qdocuments.net&quot;&gt;
        ///  &lt;tk:SingleXmlMetaData DataXml=&quot;workflow/ApproveHistory.xml&quot; TableName=&quot;_Approve_Temp&quot; ColumnCount=&quot;1&quot;/&gt;
        ///  &lt;tk:TableResolver&gt;
        ///    &lt;tk:RegResolver&gt;ApproveHistory&lt;/tk:RegResolver&gt;
        ///  &lt;/tk:TableResolver&gt;
        ///&lt;/tk:Table&gt; 的本地化字符串。
        /// </summary>
        internal static string ApproveProcessXml {
            get {
                return ResourceManager.GetString("ApproveProcessXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;tk:Table ListStyle=&quot;Table&quot; Action=&quot;List&quot; xmlns:tk=&quot;http://www.qdocuments.net&quot;&gt;
        ///  &lt;tk:SingleXmlMetaData DataXml=&quot;Workflow/StepInst.xml&quot; TableName=&quot;WF_STEP_INST_HIS&quot;/&gt;
        ///&lt;/tk:Table&gt; 的本地化字符串。
        /// </summary>
        internal static string StepHisTableXml {
            get {
                return ResourceManager.GetString("StepHisTableXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;tk:Table ListStyle=&quot;Table&quot; Action=&quot;List&quot; xmlns:tk=&quot;http://www.qdocuments.net&quot;&gt;
        ///  &lt;tk:SingleXmlMetaData DataXml=&quot;Workflow/StepInst.xml&quot;/&gt;
        ///&lt;/tk:Table&gt; 的本地化字符串。
        /// </summary>
        internal static string StepTableXml {
            get {
                return ResourceManager.GetString("StepTableXml", resourceCulture);
            }
        }
    }
}
