// ==================================================
// ==== Toolkit v1.5.6 ====
// 基于jQuery v1.4.4， 包括以下方法集合：
// - JS原型方法扩展、 jQuery方法扩展
// - Toolkit方法库： core/json/cookie/base/data/util
// ==================================================

// --------------------------------
// core/jsextend.js : String/Number/Array/Date.prototype
// --------------------------------
(function($){if(!$)return;$.extend(String.prototype,{'trim':function(){return this.replace(/(^\s*)|(\s*$)/g,'');},'ltrim':function(){return this.replace(/(^\s*)/g,'');},'rtrim':function(){return this.replace(/(\s*$)/g,'');},'trimAll':function(){return this.replace(/\s/g,'');},'left':function(len){return this.substring(0,len);},'right':function(len){if(this.length<=len){return this;}
return this.substring(this.length-len,this.length);},'reverse':function(){return this.split('').reverse().join('');},'startWith':function(start,noCase){var index=noCase?this.toLowerCase().indexOf(start.toLowerCase()):this.indexOf(start);return!index;},'endWith':function(end,noCase){return noCase?(new RegExp(end.toLowerCase()+"$").test(this.toLowerCase().trim())):(new RegExp(end+"$").test(this.trim()));},'sliceAfter':function(str){if(this.indexOf(str)<0)return'';return this.substring(this.indexOf(str)+str.length,this.length);},'sliceBefore':function(str){if(this.indexOf(str)<0)return'';return this.substring(0,this.indexOf(str));},'getByteLength':function(){return this.replace(/[^\x00-\xff]/ig,'xx').length;},'subByte':function(len,s){if(len<0||this.getByteLength()<=len){return this;}
var str=this;str=str.substr(0,len).replace(/([^\x00-\xff])/g,"\x241 ").substr(0,len).replace(/[^\x00-\xff]$/,"").replace(/([^\x00-\xff]) /g,"\x241");return str+(s||'');},'textToHtml':function(){return this.replace(/</ig,'&lt;').replace(/>/ig,'&gt;').replace(/\r\n/ig,'<br>').replace(/\n/ig,'<br>');},'htmlToText':function(){return this.replace(/<br>/ig,'\r\n');},'htmlEncode':function(){var text=this;var re={'<':'&lt;','>':'&gt;','&':'&amp;','"':'&quot;'};for(i in re){text=text.replace(new RegExp(i,'g'),re[i]);}
return text;},'htmlDecode':function(){var text=this;var re={'&lt;':'<','&gt;':'>','&amp;':'&','&quot;':'"'};for(i in re){text=text.replace(new RegExp(i,'g'),re[i]);}
return text;},'stripHtml':function(){return this.replace(/(<\/?[^>\/]*)\/?>/ig,'');},'stripScript':function(){return this.replace(/<script(.|\n)*\/script>\s*/ig,'').replace(/on[a-z]*?\s*?=".*?"/ig,'');},'replaceAll':function(os,ns){return this.replace(new RegExp(os,"gm"),ns);},'escapeReg':function(){return this.replace(new RegExp("([.*+?^=!:\x24{}()|[\\]\/\\\\])","g"),'\\\x241');},'getQueryValue':function(name){var reg=new RegExp("(^|&|\\?|#)"+name.escapeReg()+"=([^&]*)(&|\x24)","");var match=this.match(reg);return(match)?match[2]:'';},'getQueryJson':function(){if(this.lastIndexOf('?')==-1||this.right(1)=='?')return{};var query=this.substr(this.indexOf('?')+1),params=query.split('&'),len=params.length,result={},key,value,item,param;for(var i=0;i<len;i++){param=params[i].split('=');key=param[0];value=param[1];item=result[key];if('undefined'==typeof item){result[key]=unescape(value);}else if(Object.prototype.toString.call(item)=='[object Array]'){item.push(value);}else{result[key]=[item,value];}}
return result;},'getPathName':function(){return(this.lastIndexOf('?')==-1)?this.toString():this.substring(0,this.lastIndexOf('?'));},'getFilePath':function(){return this.substring(0,this.lastIndexOf('/')+1);},'getFileName':function(){return this.substring(this.lastIndexOf('/')+1);},'getFileExt':function(){return this.substring(this.lastIndexOf('.')+1);},'parseDate':function(){return(new Date()).parse(this.toString());},'parseJSON':function(){try{return!(/[^,:{}\[\]0-9.\-+Eaeflnr-u \n\r\t]/.test(this.replace(/"(\\.|[^"\\])*"/g,'')))&&eval('('+this.toString()+')');}catch(e){return false;}},'parseAttrJSON':function(){var d={},a=this.toString().split(';');for(var i=0;i<a.length;i++){if(a[i].trim()==''||a[i].indexOf(':')<1)continue;var b=a[i].split(':');if(b[0].trim()!=''&&b[1].trim()!='')d[b[0].toCamelCase()]=b[1];}
return d;},'isURL':function(){return(new RegExp(/(http[s]?|ftp):\/\/[^\/\.]+?\..+\w$/i).test(this.trim()));},'_pad':function(width,ch,side){var str=[side?'':this,side?this:''];while(str[side].length<(width?width:0)&&(str[side]=str[1]+(ch||' ')+str[0]));return str[side];},'padLeft':function(width,ch){if(this.length>=width)return this.toString();return this._pad(width,ch,0);},'padRight':function(width,ch){if(this.length>=width)return this.toString();return this._pad(width,ch,1);},'toHalfWidth':function(){return this.replace(/[\uFF01-\uFF5E]/g,function(c){return String.fromCharCode(c.charCodeAt(0)-65248);}).replace(/\u3000/g," ");},'toCamelCase':function(){if(this.indexOf('-')<0&&this.indexOf('_')<0){return this;}
return this.replace(/[-_][^-_]/g,function(match){return match.charAt(1).toUpperCase();});},'format':function(){var result=this;if(arguments.length>0){parameters=$.makeArray(arguments);$.each(parameters,function(i,n){result=result.replace(new RegExp("\\{"+i+"\\}","g"),n);});}
return result;},'substitute':function(data){if(data&&typeof(data)=='object'){return this.replace(/\{([^{}]+)\}/g,function(match,key){var value=data[key];return(value!==undefined)?''+value:'';});}else{return this.toString();}}});$.extend(Number.prototype,{'comma':function(length){if(!length||length<1)length=3;source=(''+this).split(".");source[0]=source[0].replace(new RegExp('(\\d)(?=(\\d{'+length+'})+$)','ig'),"$1,");return source.join(".");},'randomInt':function(min,max){return Math.floor(Math.random()*(max-min+1)+min);},'padLeft':function(width,ch){return(''+this).padLeft(width,ch);},'padRight':function(width,ch){return(''+this).padRight(width,ch);}});$.extend(Array.prototype,{'indexOf':function(item,it){for(var i=0;i<this.length;i++){if(item==((it)?this[i][it]:this[i]))return i;}
return-1;},'remove':function(item,it){this.removeAt(this.indexOf(item,it));},'removeAt':function(idx){if(idx>=0&&idx<this.length){for(var i=idx;i<this.length-1;i++){this[i]=this[i+1];}
this.length--;}},'removeEmpty':function(){var arr=[];for(var i=0;i<this.length;i++){if(this[i].trim()!=''){arr.push(this[i].trim());}}
return arr;},'add':function(item){if(this.indexOf(item)>-1){return false;}else{this.push(item);return true;}},'swap':function(i,j){if(i<this.length&&j<this.length&&i!=j){var item=this[i];this[i]=this[j];this[j]=item;}},'filter':function(it,item){var arr=[];for(var i=0;i<this.length;i++){if(typeof(item)=='undefined'){arr.push(this[i][it]);}else if(this[i][it]==item){arr.push(this[i]);}}
return arr;},'sortby':function(it,dt,od){var compareValues=function(v1,v2,dt,od){if(dt=='int'){v1=parseInt(v1);v2=parseInt(v2);}else if(dt=='float'){v1=parseFloat(v1);v2=parseFloat(v2);}
var ret=0;if(v1<v2)ret=1;if(v1>v2)ret=-1;if(od=='desc'){ret=0-ret;}
return ret;};var newdata=new Array();for(var i=0;i<this.length;i++){newdata[newdata.length]=this[i];}
for(var i=0;i<newdata.length;i++){var minIdx=i;var minData=(it!='')?newdata[i][it]:newdata[i];for(var j=i+1;j<newdata.length;j++){var tmpData=(it!='')?newdata[j][it]:newdata[j];var cmp=compareValues(minData,tmpData,dt,od);if(cmp<0){minIdx=j;minData=tmpData;}}
if(minIdx>i){var _child=newdata[minIdx];newdata[minIdx]=newdata[i];newdata[i]=_child;}}
return newdata;}});$.extend(Date.prototype,{'parse':function(time){if(typeof(time)=='string'){if(time.indexOf('GMT')>0||time.indexOf('gmt')>0||!isNaN(Date.parse(time))){return this.parseGMT(time);}else if(time.indexOf('UTC')>0||time.indexOf('utc')>0||time.indexOf(',')>0){return this.parseUTC(time);}else{return this.parseCommon(time);}}
return new Date();},'parseGMT':function(time){this.setTime(Date.parse(time));return this;},'parseUTC':function(time){return(new Date(time));},'parseCommon':function(time){var d=time.split(/ |T/),d1=d.length>1?d[1].split(/[^\d]/):[0,0,0],d0=d[0].split(/[^\d]/);return new Date(d0[0]-0,d0[1]-1,d0[2]-0,d1[0]-0,d1[1]-0,d1[2]-0);},'dateAdd':function(type,val){var _y=this.getFullYear();var _m=this.getMonth();var _d=this.getDate();var _h=this.getHours();var _n=this.getMinutes();var _s=this.getSeconds();switch(type){case'y':this.setFullYear(_y+val);break;case'm':this.setMonth(_m+val);break;case'd':this.setDate(_d+val);break;case'h':this.setHours(_h+val);break;case'n':this.setMinutes(_n+val);break;case's':this.setSeconds(_s+val);break;}
return this;},'dateDiff':function(type,date2){var diff=date2-this;switch(type){case'w':return diff/1000/3600/24/7;case'd':return diff/1000/3600/24;case'h':return diff/1000/3600;case'n':return diff/1000/60;case's':return diff/1000;}},'format':function(format){if(isNaN(this))return'';var o={'m+':this.getMonth()+1,'d+':this.getDate(),'h+':this.getHours(),'n+':this.getMinutes(),'s+':this.getSeconds(),'S':this.getMilliseconds(),'W':["日","一","二","三","四","五","六"][this.getDay()],'q+':Math.floor((this.getMonth()+3)/3)}
if(format.indexOf('am/pm')>=0){format=format.replace('am/pm',(o['h+']>=12)?'下午':'上午');if(o['h+']>=12)o['h+']-=12;}
if(/(y+)/.test(format)){format=format.replace(RegExp.$1,(this.getFullYear()+"").substr(4-RegExp.$1.length));}
for(var k in o){if(new RegExp("("+k+")").test(format)){format=format.replace(RegExp.$1,RegExp.$1.length==1?o[k]:("00"+o[k]).substr((""+o[k]).length));}}
return format;}});})(jQuery);
jQuery.ajaxSetup({ cache: false });
// --------------------------------
// core/jqextend.js : jQuery extend
// --------------------------------
(function($){if(!$)return;$.extend($.browser,{'client':function(){return{width:document.documentElement.clientWidth,height:document.documentElement.clientHeight,bodyWidth:document.body.clientWidth,bodyHeight:document.body.clientHeight};},'scroll':function(){return{width:document.documentElement.scrollWidth,height:document.documentElement.scrollHeight,bodyWidth:document.body.scrollWidth,bodyHeight:document.body.scrollHeight,left:Math.max(document.documentElement.scrollLeft,document.body.scrollLeft),top:Math.max(document.documentElement.scrollTop,document.body.scrollTop)};},'screen':function(){return{width:window.screen.width,height:window.screen.height};},'isMinW':function(val){return Math.min($.browser.client().bodyWidth,$.browser.client().width)<=val;},'isMinH':function(val){return Math.min($.browser.client().bodyHeight,$.browser.client().height)<=val;},'isIE6':$.browser.msie&&$.browser.version==6,'IEMode':(function(){if($.browser.msie){if(document.documentMode){return document.documentMode;}if(document.compatMode&&document.compatMode=='CSS1Compat'){return 7;}return 5;}return 0;})(),'isIPad':(/iPad/i).test(navigator.userAgent),'language':function(){return(navigator.language||navigator.userLanguage||'').toLowerCase();}});$.fn.tagName=function(){if(this.length==0)return'';return this[0].tagName.toLowerCase();};$.fn.optionText=function(){if(this.length==0)return'';var sel=this[0];if(sel.selectedIndex==-1)return'';return sel.options[sel.selectedIndex].text;};$.fn.attrJSON=function(attr){return(this.attr(attr||'rel')||'').parseAttrJSON();};$.fn.bindJqueryUI=function(action,params){if(this.size()==0)return;var elm=this;Toolkit.load('jqueryui',function(){elm[action](params);});return this;};$.fn.bindToolkitUI=function(type,params){if(this.size()==0||!Toolkit)return this;if(Toolkit.ui&&Toolkit.ui[type]){Toolkit.ui[type](this,params);}return this;};$.fn.bindToolkitUIExtend=function(file,type,params){if(this.size()==0||!Toolkit)return this;var elm=this;Toolkit.load(file,function(){if(!Toolkit.ui[type])return;Toolkit.ui[type](elm,params);});return this;};$.fn.bindToolkitData=function(type,params){if(this.size()==0||!Toolkit)return this;if(Toolkit.data&&Toolkit.data[type]){Toolkit.data[type](this,params);}return this;};})(jQuery);

// --------------------------------
// core/toolkit.core.js : Toolkit.namespace/debug/load
// --------------------------------
(function($){if(!$||window.Toolkit)return;window.Toolkit={};Toolkit.namespace=function(name,sep){var s=name.split(sep||'.'),d={},o=function(a,b,c){if(c<b.length){if(!a[b[c]]){a[b[c]]={};}
d=a[b[c]];o(a[b[c]],b,c+1);}};o(window,s,0);return d;};Toolkit.load=function(service,action,params){if($.isArray(service)){var url=service.join(',');var urlsize=service.length;var status=Toolkit.loader.checkFileLoader(url);if(status==urlsize+1){if(typeof(action)=='function')action();}else if(status>0){Toolkit.loader.addExecute(url,action);}else if(status==0){Toolkit.loader.addExecute(url,action);Toolkit.loader.fileLoader[url]=1;Toolkit.debug('开始加载JS',url);for(var i=0;i<urlsize;i++){Toolkit.load(service[i],function(){Toolkit.loader.fileLoader[url]++;if(Toolkit.loader.fileLoader[url]==urlsize+1){Toolkit.debug('完成加载JS',url);Toolkit.loader.execute(url);}});}}}else if(Toolkit.loader.serviceLibs[service]&&Toolkit.loader.serviceLibs[service].requires){Toolkit.load(Toolkit.loader.serviceLibs[service].requires,function(){Toolkit.load.run(service,action,params);});}else{Toolkit.load.run(service,action,params);}};Toolkit.load.add=function(key,data){if(Toolkit.loader.serviceLibs[key])return;Toolkit.loader.serviceLibs[key]=data;};Toolkit.load.extend=function(key,data){if(!Toolkit.loader.serviceLibs[key])return;$.extend(Toolkit.loader.serviceLibs[key],data);};Toolkit.load.setPath=function(path){Toolkit.loader.serviceBase=path;};Toolkit.load.run=function(service,act,params){var action=(typeof(act)=='string')?(function(){try{var o=eval('Toolkit.'+service);if(o&&o[act])o[act](params);}catch(e){}}):(act||function(){});if(Toolkit.loader.checkService(service)){action();return;}
var url=Toolkit.loader.getServiceUrl(service);var status=Toolkit.loader.checkFileLoader(url);if(status==2){action();}else if(status==1){Toolkit.loader.addExecute(url,action);}else if(status==0){if($('script[src="'+url+'"]').size()>0){Toolkit.loader.fileLoader[url]=2;action();}else{Toolkit.loader.addExecute(url,action);Toolkit.loader.addScript(service);}}else{Toolkit.debug('加载异常',service);}};Toolkit.loader={};Toolkit.loader.fileLoader={};Toolkit.loader.executeLoader={};Toolkit.loader.serviceBase=(function(){return $('script:last')[0].src.sliceBefore('toolkit/');})();Toolkit.loader.serviceLibs={};Toolkit.loader.checkService=function(service){if(service.isURL())return false;try{if(service.indexOf('.')>0){var o=eval('Toolkit.'+service);return(typeof(o)!='undefined');}
return false;}catch(e){return false;}};Toolkit.loader.checkFileLoader=function(url){return(url!='')?(this.fileLoader[url]||0):-1;};Toolkit.loader.getServiceUrl=function(service){var url='';if(service.isURL()){url=service;}else if(this.serviceLibs[service]){url=(this.serviceLibs[service].js.isURL())?this.serviceLibs[service].js:(this.serviceBase+this.serviceLibs[service].js);}
return url;};Toolkit.loader.execute=function(url){if(this.executeLoader[url]){for(var i=0;i<this.executeLoader[url].length;i++){this.executeLoader[url][i]();}
this.executeLoader[url]=null;}};Toolkit.loader.addExecute=function(url,action){if(typeof(action)!='function')return;if(!this.executeLoader[url])this.executeLoader[url]=[];this.executeLoader[url].push(action);};Toolkit.loader.addScript=function(service){var this_=this;if(service.isURL()){var url=service;this.getScript(url,function(){this_.fileLoader[url]=2;Toolkit.debug('完成加载JS',url);Toolkit.loader.execute(url);});}else if(this.serviceLibs[service]){if(this.serviceLibs[service].css){var url=(this.serviceLibs[service].css.isURL())?this.serviceLibs[service].css:(this.serviceBase+this.serviceLibs[service].css);if(!this.fileLoader[url]){$('head').append('<link rel="stylesheet" type="text\/css"  href="'+url+'" \/>');this.fileLoader[url]=1;Toolkit.debug('开始加载CSS',url);}}
if(this.serviceLibs[service].js){var url=(this.serviceLibs[service].js.isURL())?this.serviceLibs[service].js:(this.serviceBase+this.serviceLibs[service].js);this.getScript(url,function(){this_.fileLoader[url]=2;Toolkit.debug('完成加载JS',url);Toolkit.loader.execute(url);});}}};Toolkit.loader.getScript=function(url,onSuccess,onError){this.getRemoteScript(url,onSuccess,onError);this.fileLoader[url]=1;Toolkit.debug('开始加载JS',url);};Toolkit.loader.getRemoteScript=function(url,onSuccess,onError){var head=document.getElementsByTagName("head")[0];var script=document.createElement("script");script.type='text/javascript';script.src=url;script.onload=script.onreadystatechange=function(){if(!this.readyState||this.readyState=="loaded"||this.readyState=="complete"){if(onSuccess)onSuccess();script.onload=script.onreadystatechange=null;head.removeChild(script);}};script.onerror=function(){if(onError)onError();};head.appendChild(script);};Toolkit.debugMode=false;Toolkit.debugIndex=0;Toolkit.debug=function(a,b){if(!this.debugMode)return;if(typeof(console)=='undefined'){Toolkit.load('firebug',function(){if(b==undefined){console.log(((Date.prototype.format)?(new Date()).format('hh:nn:ss.S'):(++Toolkit.debugIndex))+', '+a);}else{console.log(((Date.prototype.format)?(new Date()).format('hh:nn:ss.S'):(++Toolkit.debugIndex))+', '+a,'=',b);}});}else{if(console&&console.log){if(b==undefined){console.log(((Date.prototype.format)?(new Date()).format('hh:nn:ss.S'):(++Toolkit.debugIndex))+', '+a);}else{console.log(((Date.prototype.format)?(new Date()).format('hh:nn:ss.S'):(++Toolkit.debugIndex))+', '+a,'=',b);}}}};Toolkit.lang={};Toolkit.lang.language='zh-cn';Toolkit.lang.text={};Toolkit.lang.get=function(dataset,name){if(name){if(this.text[dataset]){return this.text[dataset][name]||'';}else{return'';}}else{return this.text[dataset]||null;}};Toolkit.lang.set=function(dataset,name,value){if(!this.text[dataset]){this.text[dataset]={};}
if(value){this.text[dataset][name]=value;}else{this.text[dataset]=name;}};Toolkit.lang.extend=function(dataset,data){if(!this.text[dataset]){this.text[dataset]={};}
$.extend(this.text[dataset],data);};})(jQuery);

// --------------------------------
// core/toolkit.json.js : Toolkit.json
// --------------------------------
(function($){if(!$||!window.Toolkit)return;Toolkit.namespace('Toolkit.json');Toolkit.json.parse=function(data){return(new Function("return "+data))();};Toolkit.json.stringify=function(obj){var m={'\b':'\\b','\t':'\\t','\n':'\\n','\f':'\\f','\r':'\\r','"':'\\"','\\':'\\\\'},s={'array':function(x){var a=['['],b,f,i,l=x.length,v;for(i=0;i<l;i+=1){v=x[i];f=s[typeof v];if(f){v=f(v);if(typeof v=='string'){if(b){a[a.length]=','}a[a.length]=v;b=true}}}a[a.length]=']';return a.join('')},'boolean':function(x){return String(x)},'null':function(x){return'null'},'number':function(x){return isFinite(x)?String(x):'null'},'object':function(x){if(x){if(x instanceof Array){return s.array(x)}var a=['{'],b,f,i,v;for(i in x){v=x[i];f=s[typeof v];if(f){v=f(v);if(typeof v=='string'){if(b){a[a.length]=','}a.push(s.string(i),':',v);b=true}}}a[a.length]='}';return a.join('')}return'null'},'string':function(x){if(/["\\\x00-\x1f]/.test(x)){x=x.replace(/([\x00-\x1f\\"])/g,function(a,b){var c=m[b];if(c){return c}c=b.charCodeAt();return'\\u00'+Math.floor(c/16).toString(16)+(c%16).toString(16)})}return'\"'+x+'\"'}};return s.object(obj);};})(jQuery);

// --------------------------------
// core/toolkit.cookie.js : Toolkit.cookie
// --------------------------------
(function($){if(!$||!window.Toolkit)return;Toolkit.namespace('Toolkit.cookie');Toolkit.cookie.get=function(name){var cname=name+'=';var dc=document.cookie;if(dc.length>0){begin=dc.indexOf(cname);if(begin!=-1){begin+=cname.length;end=dc.indexOf(';',begin);if(end==-1)end=dc.length;return unescape(dc.substring(begin,end));}}return'';};Toolkit.cookie.del=function(name){document.cookie=name+'=; path=/; expires=Thu,01-Jan-70 00:00:01 GMT';};Toolkit.cookie.set=function(name,value,expdate){var exp=new Date();exp.setTime(exp.getTime()+(1000*60*60*24*(expdate||365)));document.cookie=name+'='+escape(value)+'; domain='+document.domain+'; path=/'+((exp==null)?' ':('; expires='+exp.toGMTString()));};})(jQuery);

// --------------------------------
// core/toolkit.base.js : Toolkit.base
// --------------------------------
(function($){if(!$||!window.Toolkit)return;Toolkit.namespace('Toolkit.base');Toolkit.base.StringBuilder=function(){this._strings=[];};$.extend(Toolkit.base.StringBuilder.prototype,{append:function(str){var aLen=arguments.length;for(var i=0;i<aLen;i++){this._strings.push(arguments[i]);}},appendFormat:function(fmt){var re=/{[0-9]+}/g;var aryMatch=fmt.match(re);var aLen=aryMatch.length;for(var i=0;i<aLen;i++){fmt=fmt.replace(aryMatch[i],arguments[parseInt(aryMatch[i].replace(/[{}]/g,""))+1]);}
this._strings.push(fmt);},toString:function(){return this._strings.join("");}});Toolkit.base.ImageLoader=function(options){this.options=$.extend({src:'',min:0.5,max:10,timer:0.1},options||{});this.minTimeout=this.options.min*1000;this.maxTimeout=this.options.max*1000;this.intervalTimer=this.options.timer*1000;this.theTimeout=0;this.loadStatus=0;this.loaderId=(new Date()).getTime();this.onLoad=this.options.onLoad||null;this.onError=this.options.onError||null;var m_this=this;this.init=function(){this.element=new Image();this.element.onload=function(){m_this.loadStatus=1;if(m_this.onLoad)m_this.onLoad();Toolkit.debug('image onload',m_this.loaderId+': '+this.width+','+this.height);}
this.element.onerror=function(){m_this.loadStatus=-1;if(m_this.onError)m_this.onError();Toolkit.debug('image onerror',m_this.loaderId);}
this.element.src=this.options.src;this.startMonitor();Toolkit.debug('image init',m_this.loaderId);};this.startMonitor=function(){var m_this=this;setTimeout(function(){m_this.checkMonitor();},this.minTimeout);};this.checkMonitor=function(){if(this.loadStatus!=0)return;this.theTimeout=this.minTimeout;this._monitor=setInterval(function(){m_this.theTimeout+=50;if(m_this.loadStatus!=0){clearInterval(m_this._monitor);}else if(m_this.element.complete){clearInterval(m_this._monitor);m_this.loadStatus=1;if(m_this.onLoad)m_this.onLoad();Toolkit.debug('image complete',m_this.loaderId+': '+m_this.element.width+','+m_this.element.height);}else if(m_this.theTimeout>=m_this.maxTimeout){clearInterval(m_this._monitor);m_this.loadStatus=-1;if(m_this.onError)m_this.onError();Toolkit.debug('image timeout',m_this.loaderId);}},m_this.intervalTimer);};this.init();};})(jQuery);

// --------------------------------
// core/toolkit.string.js : Toolkit.string
// --------------------------------
(function($){if(!$||!window.Toolkit)return;Toolkit.namespace('Toolkit.string');Toolkit.string.isUrl=function(str){return(new RegExp(/(http[s]?|ftp):\/\/[^\/\.]+?\..+\w$/i).test(str.trim()));};Toolkit.string.isDate=function(str){var result=str.match(/^(\d{1,4})(-|\/)(\d{1,2})\2(\d{1,2})$/);if(result==null)return false;var d=new Date(result[1],result[3]-1,result[4]);return(d.getFullYear()==result[1]&&d.getMonth()+1==result[3]&&d.getDate()==result[4]);};Toolkit.string.isTime=function(str){var result=str.match(/^(\d{1,2})(:)?(\d{1,2})\2(\d{1,2})$/);if(result==null)return false;if(result[1]>24||result[3]>60||result[4]>60)return false;return true;};Toolkit.string.isDateTime=function(str){var result=str.match(/^(\d{1,4})(-|\/)(\d{1,2})\2(\d{1,2}) (\d{1,2}):(\d{1,2}):(\d{1,2})$/);if(result==null)return false;var d=new Date(result[1],result[3]-1,result[4],result[5],result[6],result[7]);return(d.getFullYear()==result[1]&&(d.getMonth()+1)==result[3]&&d.getDate()==result[4]&&d.getHours()==result[5]&&d.getMinutes()==result[6]&&d.getSeconds()==result[7]);};Toolkit.string.isInteger=function(str){return(new RegExp(/^(-|\+)?\d+$/).test(str.trim()));};Toolkit.string.isPositiveInteger=function(str){return(new RegExp(/^\d+$/).test(str.trim()))&&parseInt(str)>0;};Toolkit.string.isNegativeInteger=function(str){return(new RegExp(/^-\d+$/).test(str.trim()));};Toolkit.string.isNumber=function(str){return!isNaN(str);};Toolkit.string.isEmail=function(str){return(new RegExp(/^([_a-zA-Z\d\-\.])+@([a-zA-Z0-9_-])+(\.[a-zA-Z0-9_-])+/).test(str.trim()));};Toolkit.string.isMobile=function(str){return(new RegExp(/^(13|14|15|18)\d{9}$/).test(str.trim()));};Toolkit.string.isPhone=function(str){return(new RegExp(/^(([0\+]\d{2,3}-)?(0\d{2,3})-)?(\d{7,8})(-(\d{3,}))?$/).test(str.trim()));};Toolkit.string.isAreacode=function(str){return(new RegExp(/^0\d{2,3}$/).test(str.trim()));};Toolkit.string.isPostcode=function(str){return(new RegExp(/^\d{6}$/).test(str.trim()));};Toolkit.string.isLetters=function(str){return(new RegExp(/^[A-Za-z]+$/).test(str.trim()));};Toolkit.string.isDigits=function(str){return(new RegExp(/^[1-9][0-9]+$/).test(str.trim()));};Toolkit.string.isAlphanumeric=function(str){return(new RegExp(/^[a-zA-Z0-9]+$/).test(str.trim()));};Toolkit.string.isValidString=function(str){return(new RegExp(/^[a-zA-Z0-9\s.\-_]+$/).test(str.trim()));};Toolkit.string.isLowerCase=function(str){return(new RegExp(/^[a-z]+$/).test(str.trim()));};Toolkit.string.isUpperCase=function(str){return(new RegExp(/^[A-Z]+$/).test(str.trim()));};Toolkit.string.isChinese=function(str){return(new RegExp(/^[\u4e00-\u9fa5]+$/).test(str.trim()));};Toolkit.string.isIDCard=function(str){var r15=new RegExp(/^[1-9]\d{7}((0\d)|(1[0-2]))(([0|1|2]\d)|3[0-1])\d{3}$/);var r18=new RegExp(/^[1-9]\d{5}[1-9]\d{3}((0\d)|(1[0-2]))(([0|1|2]\d)|3[0-1])\d{3}([0-9]|X|x)$/);return(r15.test(str.trim())||r18.test(str.trim()));};})(jQuery);

// --------------------------------
// core/toolkit.util.js : Toolkit.util
// --------------------------------
(function($){if(!$||!window.Toolkit)return;Toolkit.namespace('Toolkit.util');Toolkit.util.flash=function(pSwf,pBoxID,pW,pH,pVer,pSetup,pFlashvars,pParams,pAttr){Toolkit.load('swfobject',function(){swfobject.embedSWF(pSwf,pBoxID,pW,pH,pVer,pSetup||false,pFlashvars||false,pParams||false,pAttr||false);});};Toolkit.util.overlayer={};Toolkit.util.overlayer.id='util-overlayer';Toolkit.util.overlayer.status=false;Toolkit.util.overlayer.showLayer=function(op,bg){if(this.status)return false;op=(typeof(op)!='undefined')?op:0.3;bg=bg||'#000';if($('#'+this.id).length==0)$('body').append('<div id="'+this.id+'" style="width:100%;height:100%;position:absolute;top:0; left:0;right:0;bottom:0;display:none;z-index:9990;"></div>');$('#'+this.id).css({background:bg,filter:('alpha(opacity='+op*100+')'),opacity:op});this.setSize();this.status=true;};Toolkit.util.overlayer.hideLayer=function(){if(this.status)$('#'+this.id).css('display','none');this.status=false;};Toolkit.util.overlayer.setSize=function(){$('#'+this.id).css({width:'100%',height:$(document).height()+'px',display:'block'});};Toolkit.util.overlayer.resize=function(){if(this.status){$('#'+this.id).css('display','none');this.setSize();}};$(window).resize(function(){Toolkit.util.overlayer.resize();});})(jQuery);

// --------------------------------
// core/toolkit.stat.js : Toolkit.stat
// --------------------------------
(function($){if(!$||!window.Toolkit)return;Toolkit.namespace('Toolkit.stat');Toolkit.stat.funcStat={};Toolkit.stat.addFuncStat=function(name){if(!this.funcStat[name]||this.funcStat[name]<100000000){this.funcStat[name]=(new Date()).getTime();}else{this.funcStat[name]=(new Date()).getTime()-this.funcStat[name];}};})(jQuery);

// --------------------------------
// core/toolkit.dataset.js : Toolkit.dataset
// --------------------------------
(function($){if(!$||!window.Toolkit)return;Toolkit.namespace('Toolkit.dataset');Toolkit.dataset.indexId=0;Toolkit.dataset.getDataSetId=function(){this.indexId++;return'DS'+this.indexId.padLeft(4,'0');};Toolkit.dataset.initForm=function(frm){var dataSetId=this.getDataSetId();frm.attr('dataSet',dataSetId);var tables=(frm.attr('dataTables')||'').trim().split(',').removeEmpty();var fields=(frm.attr('dataFields')||'').trim().split(';').removeEmpty();this[dataSetId]={};this[dataSetId].tables=tables;for(var i=0;i<tables.length;i++){var f=fields[i]||'';this.initTable(dataSetId,tables[i],fields[i].split(','));}};Toolkit.dataset.initTable=function(dataSetId,table,fields){this[dataSetId][table]={};this[dataSetId][table].fields=fields;this[dataSetId][table].elements=[];var tableElement=$('#'+table);if(tableElement.tagName()=='table'){var that=this;tableElement.find('tbody.list tr').each(function(){that.addElement(dataSetId,$(this),table,fields);});}else{this.addElement(dataSetId,tableElement,table,fields);}};Toolkit.dataset.addElement=function(dataSetId,elm,table,fields){var element={};for(var i=0;i<fields.length;i++){var field=fields[i];var fieldElm=elm.find('[name='+field+']');if(fieldElm.size()==0)fieldElm=elm.find('#'+field);element[field]=fieldElm;}
this[dataSetId][table].elements.push(element);};Toolkit.dataset.removeElement=function(dataSetId,table,row){this[dataSetId][table].elements.removeAt(row);};Toolkit.dataset.emptyElements=function(dataSetId,table){this[dataSetId][table].elements=[];};Toolkit.dataset.getData=function(dataSetId){Toolkit.stat.addFuncStat('Toolit.dataset.getData-'+dataSetId);var data={};for(var i=0;i<this[dataSetId].tables.length;i++){var table=this[dataSetId].tables[i];var fields=this[dataSetId][table].fields;if(this[dataSetId][table].elements.length > 0) data[table]=[];for(var j=0;j<this[dataSetId][table].elements.length;j++){var element=this[dataSetId][table].elements[j];var item={};for(var k=0;k<fields.length;k++){var field=fields[k];var elm=element[field];Toolkit.data.CheckInputValid(elm);if(elm.data('valid')&&elm.data('error')){Toolkit.page.showError(elm.closest('.tk-control').parent().attr('title'),function(){if(elm.is(':visible')){elm.focus();}});return false;}
item[field]=Toolkit.data.getElementValue(elm);}data[table].push(item);}}Toolkit.stat.addFuncStat('Toolit.dataset.getData-'+dataSetId);return data;};})(jQuery);

// --------------------------------
// core/toolkit.ui.js : Toolkit.ui
// --------------------------------


// --------------------------------
// core/toolkit.data.js : Toolkit.data
// --------------------------------


// --------------------------------
// core/toolkit.page.js : Toolkit.page
// --------------------------------


// --------------------------------
// core/toolkit.module.js : Toolkit.module
// --------------------------------


// --------------------------------
// core/toolkit.init.js : Toolkit.init
// --------------------------------
(function($){if(!$||!window.Toolkit)return;Toolkit.load.add('suggest',{js:'toolkit/ui/suggest.js',css:'toolkit/ui/suggest.css'});Toolkit.load.add('util.dialog',{js:'toolkit/util/dialog.js',css:'toolkit/util/dialog.css'});Toolkit.load.add('lhgcalendar',{js:'lhgcalendar/lhgcalendar.min.js'});Toolkit.load.add('xheditor',{js:'xheditor/xheditor-1.1.7-zh-cn.min.js'});Toolkit.load.add('swfobject',{js:'uploadify/swfobject.js'});Toolkit.load.add('uploadify',{js:'uploadify/jquery.uploadify.v2.1.4.min.js',swf:'uploadify/uploadify.swf',uploadBtn:'uploadify/upload.png',cancelBtn:'uploadify/cancel.png',requires:'swfobject'});Toolkit.load.add('dropmenu',{js:'lib/jquery.dropmenu-1.1.4.js'});Toolkit.load.add('treeview',{js:'treeview/jquery.treeview.js',css:'treeview/jquery.treeview.css'});Toolkit.load.add('jqueryui',{js:'lib/jquery-ui-1.8.16.custom.min.js'});Toolkit.load.add('firebug',{js:document.location.protocol+'//getfirebug.com/firebug-lite.js'});Toolkit.load('util.dialog');$(document).ready(function(){Toolkit.page.init();});})(jQuery);