//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.4952
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YJC.Toolkit
{


    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TkWebApp
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TkWebApp()
        {
        }

        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YJC.Toolkit.TkWebApp", typeof(TkWebApp).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   为使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   查找类似 {0}不是{1}的号码，请正确填写！ 的本地化字符串。
        /// </summary>
        internal static string BaseMobileCMsg
        {
            get
            {
                return ResourceManager.GetString("BaseMobileCMsg", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 中国移动 的本地化字符串。
        /// </summary>
        internal static string ChinaMobile
        {
            get
            {
                return ResourceManager.GetString("ChinaMobile", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 中国电信 的本地化字符串。
        /// </summary>
        internal static string ChinaTelcom
        {
            get
            {
                return ResourceManager.GetString("ChinaTelcom", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 中国联通 的本地化字符串。
        /// </summary>
        internal static string ChinaUnicom
        {
            get
            {
                return ResourceManager.GetString("ChinaUnicom", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 不能大于当前日期！ 的本地化字符串。
        /// </summary>
        internal static string CurrentDateCMsg
        {
            get
            {
                return ResourceManager.GetString("CurrentDateCMsg", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 {0}必须在{1}之后！ 的本地化字符串。
        /// </summary>
        internal static string DateAfterCMsg
        {
            get
            {
                return ResourceManager.GetString("DateAfterCMsg", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 必须是日期类型 的本地化字符串。
        /// </summary>
        internal static string DateCMsg
        {
            get
            {
                return ResourceManager.GetString("DateCMsg", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        internal static string DeleteStyle
        {
            get
            {
                return ResourceManager.GetString("DeleteStyle", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 详细 的本地化字符串。
        /// </summary>
        internal static string DetailStyle
        {
            get
            {
                return ResourceManager.GetString("DetailStyle", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 功能被禁止 的本地化字符串。
        /// </summary>
        internal static string DisableStyleErrorTitle
        {
            get
            {
                return ResourceManager.GetString("DisableStyleErrorTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 该模块的{0}功能被禁止了。 的本地化字符串。
        /// </summary>
        internal static string DisableStyleFunction
        {
            get
            {
                return ResourceManager.GetString("DisableStyleFunction", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 非法操作 的本地化字符串。
        /// </summary>
        internal static string DisableStylePageTitle
        {
            get
            {
                return ResourceManager.GetString("DisableStylePageTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 必须是Double类型 的本地化字符串。
        /// </summary>
        internal static string DoubleCMsg
        {
            get
            {
                return ResourceManager.GetString("DoubleCMsg", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 不存在 的本地化字符串。
        /// </summary>
        internal static string EasySearchNotExist
        {
            get
            {
                return ResourceManager.GetString("EasySearchNotExist", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 有二义性，请勿直接输入汉字，选择相应的项目即可 的本地化字符串。
        /// </summary>
        internal static string EasySearchVariousTwo
        {
            get
            {
                return ResourceManager.GetString("EasySearchVariousTwo", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 不是EMail地址，请正确填写 的本地化字符串。
        /// </summary>
        internal static string EmailCMsg
        {
            get
            {
                return ResourceManager.GetString("EmailCMsg", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 {0}的长度必须等于{1} 的本地化字符串。
        /// </summary>
        internal static string FixLengthCMsg
        {
            get
            {
                return ResourceManager.GetString("FixLengthCMsg", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 新建 的本地化字符串。
        /// </summary>
        internal static string InsertStyle
        {
            get
            {
                return ResourceManager.GetString("InsertStyle", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 必须是整数类型 的本地化字符串。
        /// </summary>
        internal static string IntCMsg
        {
            get
            {
                return ResourceManager.GetString("IntCMsg", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 列表 的本地化字符串。
        /// </summary>
        internal static string ListStyle
        {
            get
            {
                return ResourceManager.GetString("ListStyle", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 手机 的本地化字符串。
        /// </summary>
        internal static string MobileCName
        {
            get
            {
                return ResourceManager.GetString("MobileCName", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 手机 的本地化字符串。
        /// </summary>
        internal static string MultipleNotEmptyCMsg
        {
            get
            {
                return ResourceManager.GetString("MultipleNotEmptyCMsg", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 您没有权限访问这条数据 的本地化字符串。
        /// </summary>
        internal static string NoDataRightBody
        {
            get
            {
                return ResourceManager.GetString("NoDataRightBody", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 权限错误！ 的本地化字符串。
        /// </summary>
        internal static string NoDataRightTitle
        {
            get
            {
                return ResourceManager.GetString("NoDataRightTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 对不起，您的权限不够，无法使用该功能。 的本地化字符串。
        /// </summary>
        internal static string NoFunctionRightBody
        {
            get
            {
                return ResourceManager.GetString("NoFunctionRightBody", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 权限不够！ 的本地化字符串。
        /// </summary>
        internal static string NoFunctionRightTitle
        {
            get
            {
                return ResourceManager.GetString("NoFunctionRightTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 不能为空！ 的本地化字符串。
        /// </summary>
        internal static string NotEmptyCMsg
        {
            get
            {
                return ResourceManager.GetString("NotEmptyCMsg", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 不是邮政编码，请正确填写！ 的本地化字符串。
        /// </summary>
        internal static string PostCodeCMsg
        {
            get
            {
                return ResourceManager.GetString("PostCodeCMsg", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 {0}的值应该在{1}和{2}之间 的本地化字符串。
        /// </summary>
        internal static string RangeCBetween
        {
            get
            {
                return ResourceManager.GetString("RangeCBetween", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 {0}的值应该大于{1} 的本地化字符串。
        /// </summary>
        internal static string RangeCGreat
        {
            get
            {
                return ResourceManager.GetString("RangeCGreat", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 {0}的值应该小于{1} 的本地化字符串。
        /// </summary>
        internal static string RangeCLow
        {
            get
            {
                return ResourceManager.GetString("RangeCLow", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 不是身份证号码，请正确填写！ 的本地化字符串。
        /// </summary>
        internal static string SFZCMsg
        {
            get
            {
                return ResourceManager.GetString("SFZCMsg", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 不唯一 的本地化字符串。
        /// </summary>
        internal static string SingleValueCMsg
        {
            get
            {
                return ResourceManager.GetString("SingleValueCMsg", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 {0}的长度不能大于{1} 的本地化字符串。
        /// </summary>
        internal static string StringLengthCMsg
        {
            get
            {
                return ResourceManager.GetString("StringLengthCMsg", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 {0}在第{1}行中的数据与该行数据相同！ 的本地化字符串。
        /// </summary>
        internal static string UniqueRowCMsg
        {
            get
            {
                return ResourceManager.GetString("UniqueRowCMsg", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 修改 的本地化字符串。
        /// </summary>
        internal static string UpdateStyle
        {
            get
            {
                return ResourceManager.GetString("UpdateStyle", resourceCulture);
            }
        }

        internal static string Today
        {
            get
            {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }

        internal static string Tomorrow
        {
            get
            {
                return ResourceManager.GetString("Tomorrow", resourceCulture);
            }
        }

        internal static string Yesterday
        {
            get
            {
                return ResourceManager.GetString("Yesterday", resourceCulture);
            }
        }
    }
}
