//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YJC.Toolkit {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Html {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Html() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YJC.Toolkit.Html", typeof(Html).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;div class=&quot;checkbox&quot;&gt;
        ///    &lt;input  {0} /&gt; 
        ///    &lt;label class=&quot;checkbox-label&quot;&gt;{1}&lt;/label&gt; 
        ///&lt;/div&gt; 的本地化字符串。
        /// </summary>
        internal static string CheckBox {
            get {
                return ResourceManager.GetString("CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;div class=&quot;checkbox&quot;&gt; 
        ///    &lt;input type=&quot;checkbox&quot; class=&quot;cbl-item checkbox-label&quot;  {0} /&gt; 
        ///    &lt;label class=&quot;checkbox-label&quot;&gt;{1}&lt;/label&gt; 
        ///&lt;/div&gt; 的本地化字符串。
        /// </summary>
        internal static string CheckBoxListItem {
            get {
                return ResourceManager.GetString("CheckBoxListItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;div class=&quot;input-group date&quot; {0}&gt;
        ///  &lt;input {1}&gt;
        ///{4}
        ///  &lt;span class=&quot;input-group-addon&quot;&gt;&lt;i class=&quot;glyphicon glyphicon-{2}&quot;&gt;&lt;/i&gt;&lt;/span&gt;
        ///&lt;/div&gt;{3} 的本地化字符串。
        /// </summary>
        internal static string Datetime {
            get {
                return ResourceManager.GetString("Datetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;span class=&quot;input-group-addon&quot;&gt;&lt;i class=&quot;glyphicon glyphicon-remove&quot;&gt;&lt;/i&gt;&lt;/span&gt; 的本地化字符串。
        /// </summary>
        internal static string DateTimeDelete {
            get {
                return ResourceManager.GetString("DateTimeDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;div class=&quot;input-group&quot; data-control=&quot;EasySearch&quot; data-url=&quot;{3}&quot; data-dialog-url=&quot;{4}&quot;&gt;
        ///  &lt;input {0} /&gt;
        ///  &lt;input {1} /&gt;
        ///  &lt;span class=&quot;input-group-btn&quot;&gt;
        ///    &lt;button class=&quot;btn btn-default&quot; type=&quot;button&quot;&gt;&lt;i class=&quot;glyphicon glyphicon-search&quot;&gt;&lt;/i&gt;&lt;/button&gt;
        ///  &lt;/span&gt;
        ///&lt;/div&gt;{2} 的本地化字符串。
        /// </summary>
        internal static string EasySearch {
            get {
                return ResourceManager.GetString("EasySearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;div class=&quot;input-group&quot;&gt;
        ///  &lt;input {0}/&gt;
        ///  &lt;span class=&quot;input-group-addon&quot;&gt;{2}&lt;/span&gt;
        ///&lt;/div&gt;{1} 的本地化字符串。
        /// </summary>
        internal static string InputHintAfter {
            get {
                return ResourceManager.GetString("InputHintAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;div class=&quot;input-group&quot;&gt;
        ///  &lt;span class=&quot;input-group-addon&quot;&gt;{2}&lt;/span&gt;
        ///  &lt;input {0}/&gt;
        ///&lt;/div&gt;{1} 的本地化字符串。
        /// </summary>
        internal static string InputHintBefore {
            get {
                return ResourceManager.GetString("InputHintBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;div class=&quot;btn-group&quot;&gt;
        ///  &lt;a class=&quot;nouline cp dropdown-toggle&quot; data-toggle=&quot;dropdown&quot; aria-haspopup=&quot;true&quot; aria-expanded=&quot;false&quot;&gt;
        ///    {1} &lt;span class=&quot;caret&quot;&gt;&lt;/span&gt;
        ///  &lt;/a&gt;
        ///  &lt;ul class=&quot;dropdown-menu&quot;&gt;
        ///{0}
        ///  &lt;/ul&gt;
        ///&lt;/div&gt; 的本地化字符串。
        /// </summary>
        internal static string MenuOperator {
            get {
                return ResourceManager.GetString("MenuOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;span class=&quot;{0} easysearch-checked rad3&quot; {2}&gt;
        ///  &lt;em&gt;{1}&lt;/em&gt;
        ///  &lt;button class=&quot;close easysearch-close&quot; aria-hidden=&quot;true&quot; title=&quot;删除&quot; type=&quot;button&quot;&gt;×&lt;/button&gt;
        ///&lt;/span&gt; 的本地化字符串。
        /// </summary>
        internal static string MultiEasySearchItem {
            get {
                return ResourceManager.GetString("MultiEasySearchItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;span class=&quot;multiple-easysearch&quot;&gt;
        ///&lt;div class=&quot;fl multi-data&quot;&gt;
        ///{0}
        ///&lt;/div&gt;
        ///&lt;div class=&quot;input-group fr pl10&quot; data-control=&quot;MultipleEasySearch&quot; data-url=&quot;{3}&quot; data-dialog-url=&quot;{4}&quot;&gt;
        ///  &lt;input {1} /&gt;
        ///  &lt;span class=&quot;input-group-btn&quot;&gt;
        ///    &lt;button class=&quot;btn btn-default&quot; type=&quot;button&quot;&gt;&lt;i class=&quot;glyphicon glyphicon-search&quot;&gt;&lt;/i&gt;&lt;/button&gt;
        ///  &lt;/span&gt;
        ///&lt;/div&gt;{2}
        ///&lt;/span&gt; 的本地化字符串。
        /// </summary>
        internal static string MultipleEasySearch {
            get {
                return ResourceManager.GetString("MultipleEasySearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;div class=&quot;switch text-right&quot; data-control=&quot;CheckBox&quot;&gt;
        ///    &lt;input data-on-text=&quot;&lt;i class=&apos;icon-ok icon-white&apos;&gt;&lt;/i&gt;&quot; data-off-text=&quot;&lt;i class=&apos;icon-remove&apos;&gt;&lt;/i&gt;&quot; {0} /&gt;
        ///&lt;/div&gt; 的本地化字符串。
        /// </summary>
        internal static string Switcher {
            get {
                return ResourceManager.GetString("Switcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;ul class=&quot;operator&quot;&gt;{0}&lt;/ul&gt; 的本地化字符串。
        /// </summary>
        internal static string TileOperator {
            get {
                return ResourceManager.GetString("TileOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;div {0}&gt;
        ///  &lt;input type=&quot;file&quot; capture=&quot;camera&quot; /&gt;
        ///  &lt;div class=&quot;upload-status&quot;&gt;
        ///    &lt;div class=&quot;upload-info detail-content&quot;&gt;&lt;/div&gt;
        ///    &lt;div class=&quot;upload-image&quot;&gt;&lt;/div&gt;
        ///  &lt;/div&gt;
        ///&lt;/div&gt;{1} 的本地化字符串。
        /// </summary>
        internal static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
    }
}
