version: "3.5"
services:
  webserver:
    image: cjiangyong/tk5.5-demo:2.5
    ports:
      - "5000:5000"
    container_name: tk55demo
    networks: 
      - local-net
  database:
    image: cjiangyong/mariadb-demo:2.0
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    #volumes:
    #  - ~/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    container_name: mysql1
    networks: 
      - local-net
  proxy:
    image: cjiangyong/tk55nginx
    container_name: mynginx
    ports:
      - "80:80"
    networks: 
      - local-net

  cache:
    image: redis
    container_name: myredis
    ports:
      - "6379:6379"
    networks: 
      - local-net

networks: 
  local-net: